=============================
How to Use 7-base_geometry.py
=============================

This modules defines a base geometry class ``BaseGeometry``.

Usage
=====

``BaseGeometry`` includes no attributes, and accordingly is initialized 
with no arguments.

Importing the function from the module:
    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
    >>> bg = BaseGeometry()

Methods
=======

``BaseGeometry`` features two methods - ``area(self)`` and 
``integer_validator(self, name, value)``. ``area(...)`` is not yet
implemented.

Test valid input for integer_validator method
    >>> bg.integer_validator("my_int", 12)

Test for area faliure
    >>> bg.area()
    Traceback (most recent call last):
                   ...
    Exception: area() is not implemented

Test invalid input for integer_validator method: non-integer value
    >>> bg.integer_validator("name", "john")
    Traceback (most recent call last):
                  ...
    TypeError: name must be an integer

Test for invalid input with try statement: non-integer value
    >>> try:
    ...     bg.integer_validator("name", "John")
    ... except Exception as e:
    ...     print("[{}] {}".format(e.__class__.__name__, e))
    [TypeError] name must be an integer

Test invalid input for integer_validator method: 0 value

    >>> bg.integer_validator("age", 0)
    Traceback (most recent call last):
                  ...
    ValueError: age must be greater than 0

Test for invalid input with try statement: 0 value
    >>> try:
    ...     bg.integer_validator("age", 0)
    ... except Exception as e:
    ...     print("[{}] {}".format(e.__class__.__name__, e))
    [ValueError] age must be greater than 0

Test for zero argument passed
    >>> bg.integer_validator() # doctest: +NORMALIZE_WHITESPACE
    Traceback (most recent call last):
              ...
    TypeError: integer_validator() missing 2 required positional arguments: 
    'name' and 'value'

Test for one argument passed
    >>> bg.integer_validator("test")
    Traceback (most recent call last):
                  ...
    TypeError: integer_validator() missing 1 required positional argument: 'value'

Test for three argument passed
    >>> bg.integer_validator("test", 1, 2)
    Traceback (most recent call last):
                  ...
    TypeError: integer_validator() takes 3 positional arguments but 4 were given
